# Make sure this is set to "kotlinforforge"
modLoader="kotlinforforge"
# Make sure this is set to the appropriate version range
loaderVersion="[3,)" # Require at least 3.x
# License is REQUIRED after 1.16
license='LGPL'

[[mods]]
modId="bpmapi"
version="1.0.0"
displayName="BpmApi"
credits="The ExampleMod dev team"
authors="ExampleModAuthor"
description='''
Example mod that uses Kotlin for Forge.
'''
[[dependencies.bpmapi]]
    modId="forge"
    mandatory=true
    versionRange="[39,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.bpmapi]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,)"
    ordering="NONE"
    side="BOTH"
