# Make sure this is set to "kotlinforforge"
modLoader="kotlinforforge"
# Make sure this is set to the appropriate version range
loaderVersion="[3,)" # Require at least 3.x
# License is REQUIRED after 1.16
license='LGPL'

[[mods]]
modId="bpmmod"
version="${file.jarVersion}"
displayName="Bpm"
credits="dooZyz"
authors="dooZyz"
description='''
Automate to your heart's content.
'''
[[dependencies.bpmmod]]
    modId="forge"
    mandatory=true
    versionRange="[39,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.bpmmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,)"
    ordering="NONE"
    side="BOTH"
# [[dependencies.bpmmod]]
#     modId="bpmapi"
#     mandatory=true
#     versionRange="[1.0.0]"
#     ordering="AFTER"
#     side="BOTH"
